<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StudentLedgerTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('student_ledger')->delete();
        
        \DB::table('student_ledger')->insert(array (
            0 => 
            array (
                'ledger_id' => 1,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 2,
                'subscription_id' => 1,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-01-16 13:32:18',
                'updated_at' => '2025-01-16 13:32:18',
            ),
            1 => 
            array (
                'ledger_id' => 2,
                'attendence_id' => 1,
                'attendence_detail_id' => 1,
                'student_id' => 2,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 3,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-01-16 13:34:01',
                'updated_at' => '2025-01-16 13:34:01',
            ),
            2 => 
            array (
                'ledger_id' => 4,
                'attendence_id' => 5,
                'attendence_detail_id' => 5,
                'student_id' => 2,
                'subscription_id' => 0,
                'opening_balance' => 3,
                'credit_balance' => 2,
                'debit_balance' => 2,
                'closing_balance' => 2,
                'created_at' => '2025-01-17 17:36:24',
                'updated_at' => '2025-01-17 17:36:24',
            ),
            3 => 
            array (
                'ledger_id' => 5,
                'attendence_id' => 7,
                'attendence_detail_id' => 7,
                'student_id' => 2,
                'subscription_id' => 0,
                'opening_balance' => 2,
                'credit_balance' => 1,
                'debit_balance' => 3,
                'closing_balance' => 1,
                'created_at' => '2025-01-20 12:21:21',
                'updated_at' => '2025-01-20 12:21:21',
            ),
            4 => 
            array (
                'ledger_id' => 6,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 5,
                'subscription_id' => 2,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-01-20 12:48:39',
                'updated_at' => '2025-01-20 12:48:39',
            ),
            5 => 
            array (
                'ledger_id' => 7,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 9,
                'subscription_id' => 3,
                'opening_balance' => 0,
                'credit_balance' => 24,
                'debit_balance' => 0,
                'closing_balance' => 24,
                'created_at' => '2025-01-21 15:33:53',
                'updated_at' => '2025-01-21 15:33:53',
            ),
            6 => 
            array (
                'ledger_id' => 8,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 10,
                'subscription_id' => 4,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-01-22 04:51:41',
                'updated_at' => '2025-01-22 04:51:41',
            ),
            7 => 
            array (
                'ledger_id' => 9,
                'attendence_id' => 11,
                'attendence_detail_id' => 11,
                'student_id' => 10,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 3,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-01-22 04:54:20',
                'updated_at' => '2025-01-22 04:54:20',
            ),
            8 => 
            array (
                'ledger_id' => 10,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 11,
                'subscription_id' => 5,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-01-23 10:40:24',
                'updated_at' => '2025-01-23 10:40:24',
            ),
            9 => 
            array (
                'ledger_id' => 11,
                'attendence_id' => 12,
                'attendence_detail_id' => 12,
                'student_id' => 11,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-01-23 10:40:51',
                'updated_at' => '2025-01-23 10:40:51',
            ),
            10 => 
            array (
                'ledger_id' => 12,
                'attendence_id' => 14,
                'attendence_detail_id' => 14,
                'student_id' => 11,
                'subscription_id' => 0,
                'opening_balance' => 3,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 2,
                'created_at' => '2025-01-23 11:25:46',
                'updated_at' => '2025-01-23 11:25:46',
            ),
            11 => 
            array (
                'ledger_id' => 13,
                'attendence_id' => 15,
                'attendence_detail_id' => 15,
                'student_id' => 11,
                'subscription_id' => 0,
                'opening_balance' => 2,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 1,
                'created_at' => '2025-01-25 09:29:34',
                'updated_at' => '2025-01-25 09:29:34',
            ),
            12 => 
            array (
                'ledger_id' => 14,
                'attendence_id' => 18,
                'attendence_detail_id' => 18,
                'student_id' => 10,
                'subscription_id' => 0,
                'opening_balance' => 3,
                'credit_balance' => 2,
                'debit_balance' => 2,
                'closing_balance' => 2,
                'created_at' => '2025-01-27 09:53:18',
                'updated_at' => '2025-01-27 09:53:18',
            ),
            13 => 
            array (
                'ledger_id' => 15,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 10,
                'subscription_id' => 6,
                'opening_balance' => 2,
                'credit_balance' => 6,
                'debit_balance' => 2,
                'closing_balance' => 6,
                'created_at' => '2025-01-27 10:42:37',
                'updated_at' => '2025-01-27 10:42:37',
            ),
            14 => 
            array (
                'ledger_id' => 16,
                'attendence_id' => 19,
                'attendence_detail_id' => 19,
                'student_id' => 11,
                'subscription_id' => 0,
                'opening_balance' => 1,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 0,
                'created_at' => '2025-01-27 11:31:35',
                'updated_at' => '2025-01-27 11:31:35',
            ),
            15 => 
            array (
                'ledger_id' => 17,
                'attendence_id' => 20,
                'attendence_detail_id' => 20,
                'student_id' => 2,
                'subscription_id' => 0,
                'opening_balance' => 1,
                'credit_balance' => 0,
                'debit_balance' => 4,
                'closing_balance' => 0,
                'created_at' => '2025-01-27 11:32:11',
                'updated_at' => '2025-01-27 11:32:11',
            ),
            16 => 
            array (
                'ledger_id' => 18,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 12,
                'subscription_id' => 7,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-01-28 06:01:44',
                'updated_at' => '2025-01-28 06:01:44',
            ),
            17 => 
            array (
                'ledger_id' => 19,
                'attendence_id' => 21,
                'attendence_detail_id' => 21,
                'student_id' => 12,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-01-28 06:02:06',
                'updated_at' => '2025-01-28 06:02:06',
            ),
            18 => 
            array (
                'ledger_id' => 20,
                'attendence_id' => 22,
                'attendence_detail_id' => 22,
                'student_id' => 12,
                'subscription_id' => 0,
                'opening_balance' => 3,
                'credit_balance' => 1,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-01-28 06:03:28',
                'updated_at' => '2025-01-28 06:03:28',
            ),
            19 => 
            array (
                'ledger_id' => 21,
                'attendence_id' => 23,
                'attendence_detail_id' => 23,
                'student_id' => 12,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-01-30 06:26:50',
                'updated_at' => '2025-01-30 06:26:50',
            ),
            20 => 
            array (
                'ledger_id' => 22,
                'attendence_id' => 24,
                'attendence_detail_id' => 24,
                'student_id' => 11,
                'subscription_id' => 0,
                'opening_balance' => 0,
                'credit_balance' => 0,
                'debit_balance' => 0,
                'closing_balance' => 0,
                'created_at' => '2025-01-31 09:12:23',
                'updated_at' => '2025-01-31 09:12:23',
            ),
            21 => 
            array (
                'ledger_id' => 23,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 11,
                'subscription_id' => 8,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 3,
                'created_at' => '2025-01-31 09:42:41',
                'updated_at' => '2025-01-31 09:42:41',
            ),
            22 => 
            array (
                'ledger_id' => 26,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 13,
                'subscription_id' => 9,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-01-31 16:12:03',
                'updated_at' => '2025-02-01 16:12:03',
            ),
            23 => 
            array (
                'ledger_id' => 27,
                'attendence_id' => 27,
                'attendence_detail_id' => 27,
                'student_id' => 13,
                'subscription_id' => 0,
                'opening_balance' => 12,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 11,
                'created_at' => '2025-01-31 16:12:25',
                'updated_at' => '2025-02-01 16:12:25',
            ),
            24 => 
            array (
                'ledger_id' => 28,
                'attendence_id' => 28,
                'attendence_detail_id' => 28,
                'student_id' => 13,
                'subscription_id' => 0,
                'opening_balance' => 11,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 10,
                'created_at' => '2025-02-01 16:21:44',
                'updated_at' => '2025-02-01 16:21:44',
            ),
            25 => 
            array (
                'ledger_id' => 29,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 13,
                'subscription_id' => 10,
                'opening_balance' => 10,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 14,
                'created_at' => '2025-02-01 16:24:41',
                'updated_at' => '2025-02-01 16:24:41',
            ),
            26 => 
            array (
                'ledger_id' => 30,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 14,
                'subscription_id' => 11,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-03 06:55:56',
                'updated_at' => '2025-02-03 06:55:56',
            ),
            27 => 
            array (
                'ledger_id' => 31,
                'attendence_id' => 30,
                'attendence_detail_id' => 30,
                'student_id' => 14,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-02-04 05:34:08',
                'updated_at' => '2025-02-04 05:34:08',
            ),
            28 => 
            array (
                'ledger_id' => 32,
                'attendence_id' => 31,
                'attendence_detail_id' => 31,
                'student_id' => 14,
                'subscription_id' => 0,
                'opening_balance' => 3,
                'credit_balance' => 1,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-04 05:34:34',
                'updated_at' => '2025-02-04 05:34:34',
            ),
            29 => 
            array (
                'ledger_id' => 33,
                'attendence_id' => 32,
                'attendence_detail_id' => 32,
                'student_id' => 13,
                'subscription_id' => 0,
                'opening_balance' => 14,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 13,
                'created_at' => '2025-02-04 11:46:43',
                'updated_at' => '2025-02-04 11:46:43',
            ),
            30 => 
            array (
                'ledger_id' => 58,
                'attendence_id' => 33,
                'attendence_detail_id' => 33,
                'student_id' => 13,
                'subscription_id' => 0,
                'opening_balance' => 13,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 12,
                'created_at' => '2025-02-28 06:54:34',
                'updated_at' => '2025-02-28 06:54:34',
            ),
            31 => 
            array (
                'ledger_id' => 35,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 5,
                'subscription_id' => 12,
                'opening_balance' => 12,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 24,
                'created_at' => '2025-02-05 09:44:00',
                'updated_at' => '2025-02-05 09:44:00',
            ),
            32 => 
            array (
                'ledger_id' => 38,
                'attendence_id' => 40,
                'attendence_detail_id' => 40,
                'student_id' => 14,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-02-07 03:17:19',
                'updated_at' => '2025-02-07 03:17:19',
            ),
            33 => 
            array (
                'ledger_id' => 37,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 15,
                'subscription_id' => 13,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-07 00:59:48',
                'updated_at' => '2025-02-07 00:59:48',
            ),
            34 => 
            array (
                'ledger_id' => 43,
                'attendence_id' => 45,
                'attendence_detail_id' => 45,
                'student_id' => 14,
                'subscription_id' => 0,
                'opening_balance' => 3,
                'credit_balance' => 1,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-07 03:31:52',
                'updated_at' => '2025-02-07 03:31:52',
            ),
            35 => 
            array (
                'ledger_id' => 44,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 16,
                'subscription_id' => 14,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-18 04:30:27',
                'updated_at' => '2025-02-18 04:30:27',
            ),
            36 => 
            array (
                'ledger_id' => 45,
                'attendence_id' => 46,
                'attendence_detail_id' => 46,
                'student_id' => 16,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-02-18 04:34:51',
                'updated_at' => '2025-02-18 04:34:51',
            ),
            37 => 
            array (
                'ledger_id' => 46,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 18,
                'subscription_id' => 15,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-19 09:50:56',
                'updated_at' => '2025-02-19 09:50:56',
            ),
            38 => 
            array (
                'ledger_id' => 47,
                'attendence_id' => 47,
                'attendence_detail_id' => 47,
                'student_id' => 18,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-02-19 09:59:34',
                'updated_at' => '2025-02-19 09:59:34',
            ),
            39 => 
            array (
                'ledger_id' => 48,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 19,
                'subscription_id' => 16,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-02-19 10:35:33',
                'updated_at' => '2025-02-19 10:35:33',
            ),
            40 => 
            array (
                'ledger_id' => 49,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 20,
                'subscription_id' => 17,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-02-20 06:06:16',
                'updated_at' => '2025-02-20 06:06:16',
            ),
            41 => 
            array (
                'ledger_id' => 50,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 23,
                'subscription_id' => 18,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-02-24 11:13:59',
                'updated_at' => '2025-02-24 11:13:59',
            ),
            42 => 
            array (
                'ledger_id' => 51,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 23,
                'subscription_id' => 19,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-02-24 11:14:02',
                'updated_at' => '2025-02-24 11:14:02',
            ),
            43 => 
            array (
                'ledger_id' => 52,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 23,
                'subscription_id' => 20,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-02-24 11:14:10',
                'updated_at' => '2025-02-24 11:14:10',
            ),
            44 => 
            array (
                'ledger_id' => 53,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 25,
                'subscription_id' => 21,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-26 08:22:37',
                'updated_at' => '2025-02-26 08:22:37',
            ),
            45 => 
            array (
                'ledger_id' => 54,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 25,
                'subscription_id' => 22,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-26 08:22:46',
                'updated_at' => '2025-02-26 08:22:46',
            ),
            46 => 
            array (
                'ledger_id' => 55,
                'attendence_id' => 48,
                'attendence_detail_id' => 48,
                'student_id' => 25,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-02-26 08:27:48',
                'updated_at' => '2025-02-26 08:27:48',
            ),
            47 => 
            array (
                'ledger_id' => 56,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 26,
                'subscription_id' => 23,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-26 11:21:13',
                'updated_at' => '2025-02-26 11:21:13',
            ),
            48 => 
            array (
                'ledger_id' => 57,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 27,
                'subscription_id' => 24,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-27 08:49:50',
                'updated_at' => '2025-02-27 08:49:50',
            ),
            49 => 
            array (
                'ledger_id' => 59,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 28,
                'subscription_id' => 25,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-28 07:43:40',
                'updated_at' => '2025-02-28 07:43:40',
            ),
            50 => 
            array (
                'ledger_id' => 61,
                'attendence_id' => 49,
                'attendence_detail_id' => 49,
                'student_id' => 28,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-02-28 07:48:00',
                'updated_at' => '2025-02-28 07:48:00',
            ),
            51 => 
            array (
                'ledger_id' => 62,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 24,
                'subscription_id' => 26,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-28 08:21:30',
                'updated_at' => '2025-02-28 08:21:30',
            ),
            52 => 
            array (
                'ledger_id' => 63,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 29,
                'subscription_id' => 27,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-28 08:22:25',
                'updated_at' => '2025-02-28 08:22:25',
            ),
            53 => 
            array (
                'ledger_id' => 64,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 30,
                'subscription_id' => 28,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-02-28 08:23:15',
                'updated_at' => '2025-02-28 08:23:15',
            ),
            54 => 
            array (
                'ledger_id' => 65,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 10,
                'subscription_id' => 29,
                'opening_balance' => 6,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 10,
                'created_at' => '2025-03-06 03:38:53',
                'updated_at' => '2025-03-06 03:38:53',
            ),
            55 => 
            array (
                'ledger_id' => 66,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 31,
                'subscription_id' => 30,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-03-06 06:36:19',
                'updated_at' => '2025-03-06 06:36:19',
            ),
            56 => 
            array (
                'ledger_id' => 67,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 32,
                'subscription_id' => 31,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-03-06 07:12:29',
                'updated_at' => '2025-03-06 07:12:29',
            ),
            57 => 
            array (
                'ledger_id' => 68,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 32,
                'subscription_id' => 32,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-03-06 07:12:36',
                'updated_at' => '2025-03-06 07:12:36',
            ),
            58 => 
            array (
                'ledger_id' => 71,
                'attendence_id' => 54,
                'attendence_detail_id' => 54,
                'student_id' => 14,
                'subscription_id' => 0,
                'opening_balance' => 4,
                'credit_balance' => 0,
                'debit_balance' => 1,
                'closing_balance' => 3,
                'created_at' => '2025-03-06 07:30:32',
                'updated_at' => '2025-03-06 07:30:32',
            ),
            59 => 
            array (
                'ledger_id' => 72,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 22,
                'subscription_id' => 33,
                'opening_balance' => 0,
                'credit_balance' => 4,
                'debit_balance' => 0,
                'closing_balance' => 4,
                'created_at' => '2025-03-06 08:05:16',
                'updated_at' => '2025-03-06 08:05:16',
            ),
            60 => 
            array (
                'ledger_id' => 73,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 33,
                'subscription_id' => 34,
                'opening_balance' => 0,
                'credit_balance' => 48,
                'debit_balance' => 0,
                'closing_balance' => 48,
                'created_at' => '2025-03-12 09:37:56',
                'updated_at' => '2025-03-12 09:37:56',
            ),
            61 => 
            array (
                'ledger_id' => 74,
                'attendence_id' => 0,
                'attendence_detail_id' => 0,
                'student_id' => 2,
                'subscription_id' => 35,
                'opening_balance' => 0,
                'credit_balance' => 12,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-03-13 03:41:53',
                'updated_at' => '2025-03-13 03:41:53',
            ),
            62 => 
            array (
                'ledger_id' => 89,
                'attendence_id' => 66,
                'attendence_detail_id' => 66,
                'student_id' => 32,
                'subscription_id' => 0,
                'opening_balance' => 11,
                'credit_balance' => 1,
                'debit_balance' => 0,
                'closing_balance' => 12,
                'created_at' => '2025-03-25 08:32:22',
                'updated_at' => '2025-03-25 08:37:21',
            ),
        ));
        
        
    }
}