<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StudentInquiryMasterTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('student_inquiry_master')->delete();
        
        \DB::table('student_inquiry_master')->insert(array (
            0 => 
            array (
                'student_inquiry_id' => 6,
                'student_first_name' => 'Nidhi',
                'student_last_name' => NULL,
                'student_age' => '10',
                'category_id' => 8,
                'mobile' => '7802801090',
                'email' => 'bansipatel4041@gmail.com',
                'parent_name' => 'test',
                'plan_id' => 16,
                'batch_id' => 15,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            1 => 
            array (
                'student_inquiry_id' => 74,
                'student_first_name' => 'Anant',
                'student_last_name' => 'Shah',
                'student_age' => '8',
                'category_id' => 1,
                'mobile' => '9824773136',
                'email' => 'mysoftwaredesign@gmail.com',
                'parent_name' => 'Krunalshah',
                'plan_id' => 10,
                'batch_id' => 11,
                'communication_mode' => 3,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            2 => 
            array (
                'student_inquiry_id' => 79,
                'student_first_name' => 'Manshree',
                'student_last_name' => 'Patel',
                'student_age' => '5',
                'category_id' => 1,
                'mobile' => '9876543210',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs Patel',
                'plan_id' => 10,
                'batch_id' => 11,
                'communication_mode' => 2,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            3 => 
            array (
                'student_inquiry_id' => 80,
                'student_first_name' => 'heena',
                'student_last_name' => 'parekh',
                'student_age' => '5',
                'category_id' => 1,
                'mobile' => '9723391747',
                'email' => 'mysoftwaredesign@gmail.com',
                'parent_name' => 'krish parekh',
                'plan_id' => 10,
                'batch_id' => 11,
                'communication_mode' => 2,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            4 => 
            array (
                'student_inquiry_id' => 81,
                'student_first_name' => 'test',
                'student_last_name' => 'name',
                'student_age' => '8',
                'category_id' => 1,
                'mobile' => '9874589878',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'prerna',
                'plan_id' => 16,
                'batch_id' => 17,
                'communication_mode' => 2,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-26 10:27:50',
                'updated_at' => '2025-02-26 10:27:50',
            ),
            5 => 
            array (
                'student_inquiry_id' => 78,
                'student_first_name' => 'gianna',
                'student_last_name' => 'parekh',
                'student_age' => '5',
                'category_id' => 1,
                'mobile' => '9723391747',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'prerna parekh',
                'plan_id' => 10,
                'batch_id' => 11,
                'communication_mode' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            6 => 
            array (
                'student_inquiry_id' => 136,
                'student_first_name' => 'dimpy',
                'student_last_name' => 'shah',
                'student_age' => '10',
                'category_id' => 8,
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'Nitin',
                'plan_id' => 22,
                'batch_id' => 15,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-07 13:46:41',
                'updated_at' => '2025-03-07 13:46:41',
            ),
            7 => 
            array (
                'student_inquiry_id' => 137,
                'student_first_name' => 'Shail',
                'student_last_name' => 'Gandhi',
                'student_age' => '90',
                'category_id' => 8,
                'mobile' => '9998622503',
                'email' => 'shail.gandhi132@gmail.com',
                'parent_name' => 'Nitin',
                'plan_id' => 16,
                'batch_id' => 16,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-08 12:28:45',
                'updated_at' => '2025-03-08 12:28:45',
            ),
            8 => 
            array (
                'student_inquiry_id' => 138,
                'student_first_name' => 'Shail',
                'student_last_name' => 'Gandhi',
                'student_age' => '85',
                'category_id' => 1,
                'mobile' => '9998622503',
                'email' => 'shail.gandhi132@gmail.com',
                'parent_name' => 'NItin Gandhi',
                'plan_id' => 13,
                'batch_id' => 17,
                'communication_mode' => 3,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-08 13:03:38',
                'updated_at' => '2025-03-08 13:03:38',
            ),
            9 => 
            array (
                'student_inquiry_id' => 139,
                'student_first_name' => 'Shail',
                'student_last_name' => 'Gandhi',
                'student_age' => '20',
                'category_id' => 8,
                'mobile' => '9998622503',
                'email' => 'shail.gandhi132@gmail.com',
                'parent_name' => 'Test',
                'plan_id' => 19,
                'batch_id' => 16,
                'communication_mode' => 2,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-08 13:04:53',
                'updated_at' => '2025-03-08 13:04:53',
            ),
            10 => 
            array (
                'student_inquiry_id' => 140,
                'student_first_name' => 'Shail',
                'student_last_name' => 'Gandhi',
                'student_age' => '98',
                'category_id' => 8,
                'mobile' => '9998622503',
                'email' => 'shail.gandhi132@gmail.com',
                'parent_name' => 'Test',
                'plan_id' => 16,
                'batch_id' => 16,
                'communication_mode' => 2,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-08 13:05:47',
                'updated_at' => '2025-03-08 13:05:47',
            ),
            11 => 
            array (
                'student_inquiry_id' => 141,
                'student_first_name' => 'Shail',
                'student_last_name' => 'Gandhi',
                'student_age' => '86',
                'category_id' => 8,
                'mobile' => '9998622503',
                'email' => 'shail.gandhi132@gmail.com',
                'parent_name' => 'Test',
                'plan_id' => 16,
                'batch_id' => 15,
                'communication_mode' => 3,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-08 13:06:39',
                'updated_at' => '2025-03-08 13:06:39',
            ),
            12 => 
            array (
                'student_inquiry_id' => 142,
                'student_first_name' => 'Madhu',
                'student_last_name' => 'Pandey',
                'student_age' => '8',
                'category_id' => 1,
                'mobile' => '9876543210',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'test',
                'plan_id' => 10,
                'batch_id' => 11,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-10 12:34:10',
                'updated_at' => '2025-03-10 12:34:10',
            ),
            13 => 
            array (
                'student_inquiry_id' => 143,
                'student_first_name' => 'test',
                'student_last_name' => 'test',
                'student_age' => '8',
                'category_id' => 1,
                'mobile' => '9987654321',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'test',
                'plan_id' => 10,
                'batch_id' => 11,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-10 12:39:16',
                'updated_at' => '2025-03-10 12:39:16',
            ),
            14 => 
            array (
                'student_inquiry_id' => 144,
                'student_first_name' => 'Himani',
                'student_last_name' => 'shah',
                'student_age' => '8',
                'category_id' => 1,
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'ketan',
                'plan_id' => 13,
                'batch_id' => 12,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-12 13:28:17',
                'updated_at' => '2025-03-12 13:28:17',
            ),
            15 => 
            array (
                'student_inquiry_id' => 145,
                'student_first_name' => 'naksh',
                'student_last_name' => 'Shah',
                'student_age' => '12',
                'category_id' => 8,
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'Divya',
                'plan_id' => 19,
                'batch_id' => 15,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-12 13:29:13',
                'updated_at' => '2025-03-12 13:29:13',
            ),
            16 => 
            array (
                'student_inquiry_id' => 150,
                'student_first_name' => 'heena',
                'student_last_name' => 'patel',
                'student_age' => '13',
                'category_id' => 8,
                'mobile' => '9876543210',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'Akash',
                'plan_id' => 22,
                'batch_id' => 15,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-25 08:59:25',
                'updated_at' => '2025-03-25 08:59:25',
            ),
            17 => 
            array (
                'student_inquiry_id' => 152,
                'student_first_name' => 'Anant',
                'student_last_name' => 'shah',
                'student_age' => '7',
                'category_id' => 1,
                'mobile' => '9824773136',
                'email' => 'shahkrunal83@gmail.com',
                'parent_name' => 'krunal shah',
                'plan_id' => 13,
                'batch_id' => 11,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-25 09:04:49',
                'updated_at' => '2025-03-25 09:04:49',
            ),
            18 => 
            array (
                'student_inquiry_id' => 111,
                'student_first_name' => 'Shail',
                'student_last_name' => 'Gandhi',
                'student_age' => '9',
                'category_id' => 8,
                'mobile' => '9898098980',
                'email' => 'shail.gandhi132@gmail.com',
                'parent_name' => 'Nitin',
                'plan_id' => 16,
                'batch_id' => 16,
                'communication_mode' => 2,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-28 14:48:38',
                'updated_at' => '2025-02-28 14:48:38',
            ),
            19 => 
            array (
                'student_inquiry_id' => 112,
                'student_first_name' => 'Shail',
                'student_last_name' => 'Gandhi',
                'student_age' => '9',
                'category_id' => 8,
                'mobile' => '9998622503',
                'email' => 'sgandhi132@gmail.com',
                'parent_name' => 'Nitin',
                'plan_id' => 19,
                'batch_id' => 16,
                'communication_mode' => 3,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-28 15:02:43',
                'updated_at' => '2025-02-28 15:02:43',
            ),
            20 => 
            array (
                'student_inquiry_id' => 108,
                'student_first_name' => 'Stuti',
                'student_last_name' => 'Patel',
                'student_age' => '5',
                'category_id' => 1,
                'mobile' => '7802801090',
                'email' => 'graphics.apolloinfotech@gmail.com',
                'parent_name' => 'Nisha Patel',
                'plan_id' => 10,
                'batch_id' => 11,
                'communication_mode' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-27 13:41:47',
                'updated_at' => '2025-02-27 13:41:47',
            ),
            21 => 
            array (
                'student_inquiry_id' => 113,
                'student_first_name' => 'sss',
                'student_last_name' => 'Gandhi',
                'student_age' => '9',
                'category_id' => 8,
                'mobile' => '9998622503',
                'email' => 'shail.gandhi132@gmail.com',
                'parent_name' => 'Nitin',
                'plan_id' => 16,
                'batch_id' => 15,
                'communication_mode' => 3,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-28 15:04:31',
                'updated_at' => '2025-02-28 15:04:31',
            ),
        ));
        
        
    }
}