<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StudentMasterTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('student_master')->delete();
        
        \DB::table('student_master')->insert(array (
            0 => 
            array (
                'student_id' => 1,
                'student_first_name' => 'Anant Shah',
                'student_last_name' => '',
                'student_age' => '6',
                'mobile' => '9824773136',
                'email' => 'shahkrunal83@gmail.com',
                'parent_name' => 'Krunal Shah',
                'category_id' => 1,
                'plan_id' => 1,
                'batch_id' => 8,
                'login_id' => 'Kac1',
                'password' => '$2y$10$iY0dc7b8vcWtJpopBhZo4OwaoeIj0VBptan5Z/LhQgbUdXoCuYehq',
                'isWaiting' => 1,
                'isRegister' => 0,
                'isPaid' => 0,
                'communication_mode' => 2,
                'token' => 'jDbwnVaHVny1VRGPqkbFX9iI9CovTNzm0EsS6l3Ouhvy4GEPa6lI8H0heauSwiEN',
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-16 13:17:03',
                'updated_at' => '2025-01-20 11:21:31',
            ),
            1 => 
            array (
                'student_id' => 2,
                'student_first_name' => 'Anant Shah',
                'student_last_name' => '',
                'student_age' => '6',
                'mobile' => '9824773136',
                'email' => 'shahkrunal83@gmail.com',
                'parent_name' => 'Krunal Shah',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 11,
                'login_id' => 'Kac2',
                'password' => '$2y$10$t7Z6LXHaILsdRLT2AAnGlORc9CN4fW8SH9rBdjUunVZXkNp1ZzN6C',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 2,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 0,
                'isDelete' => 0,
                'created_at' => '2025-01-16 13:29:15',
                'updated_at' => '2025-03-13 03:41:53',
            ),
            2 => 
            array (
                'student_id' => 3,
                'student_first_name' => 'Bansari',
                'student_last_name' => '',
                'student_age' => '10',
                'mobile' => '7802801090',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 10,
                'login_id' => 'Kac3',
                'password' => '$2y$10$Q.Av2KZRhtDysqIVZAbp6e0G3iPcsR9ytETASQZ5CHd17GraHK7fy',
                'isWaiting' => 1,
                'isRegister' => 0,
                'isPaid' => 0,
                'communication_mode' => 1,
                'token' => 'uegcOmNR2gfEpChztNg6urUugk1hOwnmQDjxOPOAfuSHmUrxhIs2dzmPQaRxnb8i',
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-16 13:38:46',
                'updated_at' => '2025-01-21 05:33:24',
            ),
            3 => 
            array (
                'student_id' => 4,
                'student_first_name' => 'akhkkhgklgh',
                'student_last_name' => '',
                'student_age' => '5',
                'mobile' => '983098096860896',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'kjjskdlgjgljgljg',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 12,
                'login_id' => 'Kac4',
                'password' => '$2y$10$lbjqbA4KUh2YWVJkQkWMY.rK2wvhwUkYnshloBSPoUvuWYL3ZQdbe',
                'isWaiting' => 1,
                'isRegister' => 0,
                'isPaid' => 0,
                'communication_mode' => 1,
                'token' => 'YxMsXZALhHharPLY7HRooJZLBL2ue5zi6UkRTrs1TwhwGS9B5htQ00twfJWlBlOe',
                'token_time' => '2025-03-25 06:11:22',
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-17 08:04:05',
                'updated_at' => '2025-03-25 06:11:22',
            ),
            4 => 
            array (
                'student_id' => 5,
                'student_first_name' => 'Bansari',
                'student_last_name' => '',
                'student_age' => '-6',
                'mobile' => '7802801090',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 11,
                'login_id' => 'Kac5',
                'password' => '$2y$10$nG8k66e/cFSQAxoJGSSda..5ePI.o.NKlezBGusCS6Rd/cp1Z.fv6',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-17 10:10:35',
                'updated_at' => '2025-02-05 09:44:00',
            ),
            5 => 
            array (
                'student_id' => 7,
                'student_first_name' => 'test123',
                'student_last_name' => '',
                'student_age' => '5',
                'mobile' => '9874589788',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'josheph',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 12,
                'login_id' => 'Kac7',
                'password' => '$2y$10$HpLC5hy/v8Uiim6D9hTFl.0QLqCCiR/vhw68wsM2ixj4.8rpyRwcm',
                'isWaiting' => 1,
                'isRegister' => 0,
                'isPaid' => 0,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-17 11:38:45',
                'updated_at' => '2025-02-19 09:32:00',
            ),
            6 => 
            array (
                'student_id' => 8,
                'student_first_name' => 'Sneh shah',
                'student_last_name' => '',
                'student_age' => '8',
                'mobile' => '9824773136',
                'email' => 'shahkrunal83@gmail.com',
                'parent_name' => 'Krunal Shah',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac8',
                'password' => '$2y$10$IZTXWrC9mMuQGvOGjx8U4uJankNRXd74r8tZUDAeK5XITk4QzkAtK',
                'isWaiting' => 1,
                'isRegister' => 0,
                'isPaid' => 0,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-21 15:31:49',
                'updated_at' => '2025-01-21 15:31:49',
            ),
            7 => 
            array (
                'student_id' => 9,
                'student_first_name' => 'Mahi shah',
                'student_last_name' => '',
                'student_age' => '8',
                'mobile' => '9409202530',
                'email' => 'mysoftwaredesign@gmail.com',
                'parent_name' => 'Bhavi shah',
                'category_id' => 1,
                'plan_id' => 14,
                'batch_id' => 12,
                'login_id' => 'Kac9',
                'password' => '$2y$10$JHfvPyAkCMrSOTMJrWMDUe0CQeH8x6YEOSDRn/fIV0oYFQNIYfZ.G',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-21 15:33:31',
                'updated_at' => '2025-01-21 15:33:53',
            ),
            8 => 
            array (
                'student_id' => 10,
                'student_first_name' => 'Bansari Patel',
                'student_last_name' => '',
                'student_age' => '6',
                'mobile' => '7802801090',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 1,
                'plan_id' => 16,
                'batch_id' => 11,
                'login_id' => 'Kac10',
                'password' => '$2y$10$xBX19MNUVrMdrR3OjEWi1uwwg2FeGBGDiaIKY1mPsfOsaSBsSupf.',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-22 04:47:40',
                'updated_at' => '2025-03-06 03:38:53',
            ),
            9 => 
            array (
                'student_id' => 11,
                'student_first_name' => 'Nidhi',
                'student_last_name' => '',
                'student_age' => '10',
                'mobile' => '7802801090',
                'email' => 'bansipatel4041@gmail.com',
                'parent_name' => 'Mrs. Prajapati',
                'category_id' => 8,
                'plan_id' => 10,
                'batch_id' => 15,
                'login_id' => 'Kac11',
                'password' => '$2y$10$F7ovQF4WBC7rATuNeJTuoOezgip8car2.gFDQjW4YLgg2fnufDVSG',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => 'oacEm76ShBsiH0k0b7QKbwKNmHwYgsvZvTraw22iVCu3tgOiaNattyoAnY2Rdxe7',
                'token_time' => '2025-02-05 17:44:26',
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-23 10:40:06',
                'updated_at' => '2025-02-05 11:44:26',
            ),
            10 => 
            array (
                'student_id' => 12,
                'student_first_name' => 'Janvi',
                'student_last_name' => '',
                'student_age' => '7',
                'mobile' => '9876543210',
                'email' => 'bansipatel4041@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac12',
                'password' => '$2y$10$LTj7yunnOkrsxpYhi3IQ4OTAvyVc79KvwGZ8nLO4DZxcjTpeWJuQe',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-28 06:00:54',
                'updated_at' => '2025-01-28 06:01:44',
            ),
            11 => 
            array (
                'student_id' => 13,
                'student_first_name' => 'gianna',
                'student_last_name' => '',
                'student_age' => '7',
                'mobile' => '9874589788',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'prerna',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac13',
                'password' => '$2y$10$rOEOgCvaM9xkgrf68gLBSuUarnb6F88Pmktl/Hbh7cUpA7UqkUySW',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-01 16:11:37',
                'updated_at' => '2025-02-05 12:16:54',
            ),
            12 => 
            array (
                'student_id' => 14,
                'student_first_name' => 'Bansari',
                'student_last_name' => '',
                'student_age' => '10',
                'mobile' => '9924507310',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 8,
                'plan_id' => 16,
                'batch_id' => 15,
                'login_id' => 'Kac14',
                'password' => '$2y$10$fHNppSwk0ArtK6vDcyZxceF1UK7E.grbi2B0SqD/Wpq.pabpDmUZ6',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 2,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 0,
                'isDelete' => 0,
                'created_at' => '2025-02-03 06:55:42',
                'updated_at' => '2025-02-03 06:55:56',
            ),
            13 => 
            array (
                'student_id' => 15,
                'student_first_name' => 'Diya',
                'student_last_name' => '',
                'student_age' => '10',
                'mobile' => '9924501090',
                'email' => 'bansipatel4041@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 10,
                'login_id' => 'Kac15',
                'password' => '$2y$10$hJRB5DQ0Dxry8D96cOOBEe9mVZWONrlPgZ3ye3U68au330MV1y7rW',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 0,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-07 00:59:25',
                'updated_at' => '2025-02-07 00:59:48',
            ),
            14 => 
            array (
                'student_id' => 16,
                'student_first_name' => 'Diya',
                'student_last_name' => '',
                'student_age' => '10',
                'mobile' => '9852364710',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 8,
                'plan_id' => 16,
                'batch_id' => 15,
                'login_id' => 'Kac16',
                'password' => '$2y$10$1mciXjzYd7aqLYrOMM9UeOfTOmNtz8TcwvfZRg21h0.2wRgvog9RS',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-18 04:28:59',
                'updated_at' => '2025-02-18 04:30:27',
            ),
            15 => 
            array (
                'student_id' => 17,
                'student_first_name' => 'John',
                'student_last_name' => '',
                'student_age' => '8',
                'mobile' => '9898098980',
                'email' => 'kittenart15@gmail.com',
                'parent_name' => 'Jenny',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac17',
                'password' => '$2y$10$TkFd4nnu4/zJcFltgo8g3OIECLn6CwtXbCV6nDBpOf5UZcq33q5me',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 0,
                'communication_mode' => 2,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-19 09:43:16',
                'updated_at' => '2025-02-19 09:44:05',
            ),
            16 => 
            array (
                'student_id' => 18,
                'student_first_name' => 'Shail',
                'student_last_name' => '',
                'student_age' => '8',
                'mobile' => '9898098980',
                'email' => 'sgandhi007@yopmail.com',
                'parent_name' => 'Manushi',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac18',
                'password' => '$2y$10$dyG44HXC0ZGpFQ8i2Rqxd.J4pzf8WxNKXufMjE6u8wd8znl0QrUM6',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 2,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-19 09:48:55',
                'updated_at' => '2025-02-19 09:50:56',
            ),
            17 => 
            array (
                'student_id' => 19,
                'student_first_name' => 'Manushi',
                'student_last_name' => '',
                'student_age' => '9',
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'Nitin',
                'category_id' => 8,
                'plan_id' => 22,
                'batch_id' => 15,
                'login_id' => 'Kac19',
                'password' => '$2y$10$2uKHMlZkZm4dWgr8kLhuLOk.Qx42jtM8iYaZ2ZZQXVp93694b6JtK',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-19 10:30:09',
                'updated_at' => '2025-02-19 10:35:33',
            ),
            18 => 
            array (
                'student_id' => 20,
                'student_first_name' => 'dipali',
                'student_last_name' => '',
                'student_age' => '8',
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'kishan',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 11,
                'login_id' => 'Kac20',
                'password' => '$2y$10$OiHVagWxmssjfFO9rhFr0eJmVkpqOYy2blUcXeDtx45SSTp9MNYfG',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-20 06:04:31',
                'updated_at' => '2025-02-20 06:06:16',
            ),
            19 => 
            array (
                'student_id' => 21,
                'student_first_name' => 'dipali',
                'student_last_name' => '',
                'student_age' => '8',
                'mobile' => '9802545836',
                'email' => 'kush.shahkd@gmail.com',
                'parent_name' => 'kishan',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 12,
                'login_id' => 'Kac21',
                'password' => '$2y$10$S8HiGNnTYTfaf9TUQi5Ar.f45KTr66VgxieJ.9M1zD.GTryrbud.O',
                'isWaiting' => 1,
                'isRegister' => 0,
                'isPaid' => 0,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-20 06:33:44',
                'updated_at' => '2025-02-20 06:33:44',
            ),
            20 => 
            array (
                'student_id' => 22,
                'student_first_name' => 'Aadhya',
                'student_last_name' => '',
                'student_age' => '6',
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'Divya',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac22',
                'password' => '$2y$10$Dz0/R0Th.vTQ73WPnwb33.r8ICm5Cv83mL1GM8pPYuXPfP/ivt2Nm',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-20 19:14:26',
                'updated_at' => '2025-03-06 08:05:16',
            ),
            21 => 
            array (
                'student_id' => 23,
                'student_first_name' => 'Manushi',
                'student_last_name' => 'shah',
                'student_age' => '8',
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'Nitin',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 11,
                'login_id' => 'Kac23',
                'password' => '$2y$10$bv8RbT0RyVL1XFRz4/tcDe8czdR3v8J1fasz1d6CbXxY3UvmmASSm',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-24 11:12:21',
                'updated_at' => '2025-02-24 11:13:59',
            ),
            22 => 
            array (
                'student_id' => 24,
                'student_first_name' => 'gianna',
                'student_last_name' => 'parekh',
                'student_age' => '5',
                'mobile' => '9723391747',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'prerna parekh',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac24',
                'password' => '$2y$10$.zMzisfHoLNO3i//JQ9KguhioZnkbaqbSB1AQD8dGM0iU0a.SoYte',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-26 04:22:26',
                'updated_at' => '2025-02-28 08:21:30',
            ),
            23 => 
            array (
                'student_id' => 25,
                'student_first_name' => 'Mansi',
                'student_last_name' => 'Patel',
                'student_age' => '8',
                'mobile' => '9876543210',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Neha Patel',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac25',
                'password' => '$2y$10$FhuXO4mB8HtOTy1bJCUvBe/ShvJjUiDf/FIPQzKvWAfnqO.gFUZEa',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 2,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-26 08:22:15',
                'updated_at' => '2025-02-26 08:22:37',
            ),
            24 => 
            array (
                'student_id' => 26,
                'student_first_name' => 'Anant',
                'student_last_name' => 'Shah',
                'student_age' => '5',
                'mobile' => '9824773133',
                'email' => 'shahkrunal83@gmail.com',
                'parent_name' => 'Krunal Shah',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac26',
                'password' => '$2y$10$6zbpgQmFfq.nbp.CqA1h.O7BqA/bQF3i/ND48bDd0yScpWuzKZzSS',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 3,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-26 11:20:19',
                'updated_at' => '2025-02-26 11:21:13',
            ),
            25 => 
            array (
                'student_id' => 27,
                'student_first_name' => 'Nidhi',
                'student_last_name' => 'Shah',
                'student_age' => '6',
                'mobile' => '7896541232',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs Shah',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac27',
                'password' => '$2y$10$FKpjxI9qTioUdRT4Hpi2Le//FmuNkj6p.v3C0KdMv2S5HBPb1i1iS',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 3,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-27 08:49:36',
                'updated_at' => '2025-02-27 08:49:50',
            ),
            26 => 
            array (
                'student_id' => 28,
                'student_first_name' => 'Shreya',
                'student_last_name' => 'Shah',
                'student_age' => '9',
                'mobile' => '7894654321',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs Shah',
                'category_id' => 8,
                'plan_id' => 16,
                'batch_id' => 15,
                'login_id' => 'Kac28',
                'password' => '$2y$10$DugVguO7rM11KYEfyAF/KOtIkfOBXKWJ6D8rCgX/oTYSVga3mN.fm',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-28 07:43:17',
                'updated_at' => '2025-02-28 07:43:40',
            ),
            27 => 
            array (
                'student_id' => 29,
                'student_first_name' => 'Ditya',
                'student_last_name' => 'Shah',
                'student_age' => '10',
                'mobile' => '8795431200',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Dinesh shah',
                'category_id' => 8,
                'plan_id' => 16,
                'batch_id' => 15,
                'login_id' => 'Kac29',
                'password' => '$2y$10$KXdCXIJDDctGDg.rtGU90u4CJ2lMzcjZ3JN389HPreiabf6gYlfs6',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 3,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-28 08:21:58',
                'updated_at' => '2025-02-28 08:22:25',
            ),
            28 => 
            array (
                'student_id' => 30,
                'student_first_name' => 'Ditya',
                'student_last_name' => 'Shah',
                'student_age' => '10',
                'mobile' => '8795431200',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Dinesh shah',
                'category_id' => 8,
                'plan_id' => 16,
                'batch_id' => 15,
                'login_id' => 'Kac30',
                'password' => '$2y$10$zGtbsTsjP5a59Pxa/HILo.Jh4QbCnqu6bdzFXjgP8Qo.e70M07QXC',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 3,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-28 08:23:00',
                'updated_at' => '2025-02-28 08:23:15',
            ),
            29 => 
            array (
                'student_id' => 31,
                'student_first_name' => 'test',
                'student_last_name' => 'parekh',
                'student_age' => '6',
                'mobile' => '9874589788',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'prerna parekh',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'login_id' => 'Kac31',
                'password' => '$2y$10$OVPc2OPEWdLjYLsymkEQie8srhOB8cepuTFkYqr2hieC9typlaGqC',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 3,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-06 06:35:49',
                'updated_at' => '2025-03-06 06:36:19',
            ),
            30 => 
            array (
                'student_id' => 32,
                'student_first_name' => 'khushi',
                'student_last_name' => 'shah',
                'student_age' => '6',
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'Divya',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 11,
                'login_id' => 'Kac32',
                'password' => '$2y$10$6syuNRWtsCoNJ71em/ipue0jJ7wY4Mx8v4f2tgMnQK5WJZYI5bJma',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 0,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-06 07:12:10',
                'updated_at' => '2025-03-06 07:12:29',
            ),
            31 => 
            array (
                'student_id' => 33,
                'student_first_name' => 'keta',
                'student_last_name' => 'shah',
                'student_age' => '10',
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'Jayesh',
                'category_id' => 8,
                'plan_id' => 19,
                'batch_id' => 15,
                'login_id' => 'Kac33',
                'password' => '$2y$10$D8iYa6PitQcoaNpwi88nSuS5VPEFi1WeUU9WkMtXzMuPkWNcmpbiC',
                'isWaiting' => 0,
                'isRegister' => 1,
                'isPaid' => 1,
                'communication_mode' => 1,
                'token' => NULL,
                'token_time' => NULL,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-12 09:37:35',
                'updated_at' => '2025-03-12 09:37:56',
            ),
        ));
        
        
    }
}