<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TrialMasterTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('trial_master')->delete();
        
        \DB::table('trial_master')->insert(array (
            0 => 
            array (
                'trialclass_student_id' => 2,
                'student_first_name' => 'test user',
                'student_last_name' => '',
                'student_age' => '8',
                'mobile' => '9874587878',
                'email' => 'testuser@gmail.com',
                'parent_name' => 'parent name',
                'category_id' => 1,
                'plan_id' => 1,
                'batch_id' => 5,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-10 11:08:12',
                'updated_at' => '2025-01-10 11:08:12',
            ),
            1 => 
            array (
                'trialclass_student_id' => 3,
                'student_first_name' => 'anica',
                'student_last_name' => '',
                'student_age' => '5',
                'mobile' => '9874589788',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'akash',
                'category_id' => 1,
                'plan_id' => 7,
                'batch_id' => 8,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-10 17:15:07',
                'updated_at' => '2025-01-10 17:15:07',
            ),
            2 => 
            array (
                'trialclass_student_id' => 6,
                'student_first_name' => 'Bansari',
                'student_last_name' => '',
                'student_age' => '10',
                'mobile' => '7802801090',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'no_of_reminder_sent' => 2,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-17 12:45:12',
                'updated_at' => '2025-01-20 04:48:37',
            ),
            3 => 
            array (
                'trialclass_student_id' => 7,
                'student_first_name' => 'Bansari',
                'student_last_name' => '',
                'student_age' => '5',
                'mobile' => '98765432100000000000',
                'email' => 'bansipatel4041@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'no_of_reminder_sent' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-25 13:06:25',
                'updated_at' => '2025-01-25 13:07:54',
            ),
            4 => 
            array (
                'trialclass_student_id' => 8,
                'student_first_name' => 'test123',
                'student_last_name' => '',
                'student_age' => '5',
                'mobile' => '9874587888',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'manisha',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 10,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-25 13:06:49',
                'updated_at' => '2025-01-25 13:06:49',
            ),
            5 => 
            array (
                'trialclass_student_id' => 9,
                'student_first_name' => 'gianna',
                'student_last_name' => '',
                'student_age' => '8',
                'mobile' => '9723391747',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'sjhgjkgh',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 13,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-25 13:08:49',
                'updated_at' => '2025-01-25 13:08:49',
            ),
            6 => 
            array (
                'trialclass_student_id' => 10,
                'student_first_name' => 'test123',
                'student_last_name' => '',
                'student_age' => '5',
                'mobile' => '9874589878',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'william',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 13,
                'no_of_reminder_sent' => 1,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-25 13:10:33',
                'updated_at' => '2025-01-27 07:50:06',
            ),
            7 => 
            array (
                'trialclass_student_id' => 11,
                'student_first_name' => 'test',
                'student_last_name' => '',
                'student_age' => '10',
                'mobile' => '9852364710',
                'email' => 'dev1.apolloinfotech@gmail.com',
                'parent_name' => 'test',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-28 05:55:20',
                'updated_at' => '2025-01-28 05:55:20',
            ),
            8 => 
            array (
                'trialclass_student_id' => 12,
                'student_first_name' => 'Bansari',
                'student_last_name' => '',
                'student_age' => '22',
                'mobile' => '7802801090',
                'email' => 'bansipatel4041@gmail.com',
                'parent_name' => 'Mrs. Patel',
                'category_id' => 1,
                'plan_id' => 10,
                'batch_id' => 11,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-01-31 10:48:30',
                'updated_at' => '2025-01-31 10:48:30',
            ),
            9 => 
            array (
                'trialclass_student_id' => 14,
                'student_first_name' => 'Navya',
                'student_last_name' => '',
                'student_age' => '6',
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'Manushi Shah',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 12,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-17 08:08:49',
                'updated_at' => '2025-02-17 08:08:49',
            ),
            10 => 
            array (
                'trialclass_student_id' => 15,
                'student_first_name' => 'Navya',
                'student_last_name' => '',
                'student_age' => '6',
                'mobile' => '9802545836',
                'email' => 'maanukush@gmail.com',
                'parent_name' => 'Manushi shah',
                'category_id' => 1,
                'plan_id' => 13,
                'batch_id' => 12,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-17 08:10:38',
                'updated_at' => '2025-02-17 08:10:38',
            ),
            11 => 
            array (
                'trialclass_student_id' => 25,
                'student_first_name' => 'Stuti',
                'student_last_name' => 'Patel',
                'student_age' => '8',
                'mobile' => '9876543210',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Payal',
                'category_id' => 1,
                'plan_id' => 0,
                'batch_id' => 0,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-05 06:17:39',
                'updated_at' => '2025-03-05 06:17:39',
            ),
            12 => 
            array (
                'trialclass_student_id' => 24,
                'student_first_name' => 'Bansari',
                'student_last_name' => 'Patel',
                'student_age' => '9',
                'mobile' => '9876543210',
                'email' => 'dev1.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs Patel',
                'category_id' => 8,
                'plan_id' => 0,
                'batch_id' => 0,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-05 06:15:40',
                'updated_at' => '2025-03-05 06:15:40',
            ),
            13 => 
            array (
                'trialclass_student_id' => 23,
                'student_first_name' => 'Sneh',
                'student_last_name' => 'Shah',
                'student_age' => '14',
                'mobile' => '9824773136',
                'email' => 'shahkrunal83@gmail.com',
                'parent_name' => 'Krunal Shah',
                'category_id' => 8,
                'plan_id' => 0,
                'batch_id' => 0,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-26 11:09:10',
                'updated_at' => '2025-02-26 11:09:10',
            ),
            14 => 
            array (
                'trialclass_student_id' => 22,
                'student_first_name' => 'Dhruvi',
                'student_last_name' => 'Prajapati',
                'student_age' => '8',
                'mobile' => '9876543210',
                'email' => 'dev5.apolloinfotech@gmail.com',
                'parent_name' => 'Mrs Prajapati',
                'category_id' => 1,
                'plan_id' => 0,
                'batch_id' => 0,
                'no_of_reminder_sent' => 2,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-02-26 07:39:43',
                'updated_at' => '2025-02-26 08:13:19',
            ),
            15 => 
            array (
                'trialclass_student_id' => 30,
                'student_first_name' => 'student',
                'student_last_name' => 'name',
                'student_age' => '6',
                'mobile' => '9876543210',
                'email' => 'dev4.apolloinfotech@gmail.com',
                'parent_name' => 'parent name',
                'category_id' => 1,
                'plan_id' => 0,
                'batch_id' => 0,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-25 05:11:57',
                'updated_at' => '2025-03-25 05:11:57',
            ),
            16 => 
            array (
                'trialclass_student_id' => 29,
                'student_first_name' => 'Bansari',
                'student_last_name' => 'Patel',
                'student_age' => '9',
                'mobile' => '9987654321',
                'email' => 'dev1.apolloinfotech@gmail.com',
                'parent_name' => 'test',
                'category_id' => 8,
                'plan_id' => 0,
                'batch_id' => 0,
                'no_of_reminder_sent' => 0,
                'status' => 0,
                'iStatus' => 1,
                'isDelete' => 0,
                'created_at' => '2025-03-10 08:40:11',
                'updated_at' => '2025-03-10 08:40:11',
            ),
        ));
        
        
    }
}